/**
 * HumanTyper — Built-in Synonym Dictionary (150+ entries)
 * Used for word substitution / draft correction simulation.
 */

// eslint-disable-next-line no-unused-vars
const SYNONYMS = {
  // ── Size / Scale ──
  big: ['large', 'huge', 'enormous', 'massive', 'substantial'],
  large: ['big', 'huge', 'sizable', 'vast', 'extensive'],
  small: ['little', 'tiny', 'minor', 'slight', 'compact'],
  little: ['small', 'tiny', 'minor', 'slight', 'brief'],
  tiny: ['small', 'little', 'minuscule', 'minute'],
  huge: ['enormous', 'massive', 'immense', 'vast', 'colossal'],

  // ── Quality ──
  good: ['great', 'fine', 'excellent', 'positive', 'beneficial'],
  great: ['excellent', 'wonderful', 'fantastic', 'remarkable', 'outstanding'],
  bad: ['poor', 'terrible', 'awful', 'negative', 'dreadful'],
  terrible: ['awful', 'dreadful', 'horrible', 'atrocious'],
  nice: ['pleasant', 'lovely', 'agreeable', 'delightful', 'enjoyable'],
  beautiful: ['gorgeous', 'stunning', 'lovely', 'attractive', 'elegant'],
  ugly: ['unattractive', 'unsightly', 'hideous', 'grotesque'],

  // ── Speed / Movement ──
  fast: ['quick', 'rapid', 'swift', 'speedy', 'hasty'],
  quick: ['fast', 'rapid', 'swift', 'prompt', 'brisk'],
  slow: ['gradual', 'leisurely', 'unhurried', 'sluggish', 'steady'],
  run: ['sprint', 'dash', 'jog', 'race', 'rush'],
  walk: ['stroll', 'wander', 'stride', 'amble', 'trek'],

  // ── Common Verbs ──
  make: ['create', 'build', 'produce', 'construct', 'form'],
  get: ['obtain', 'acquire', 'receive', 'gain', 'secure'],
  give: ['provide', 'offer', 'present', 'supply', 'deliver'],
  take: ['grab', 'seize', 'acquire', 'claim', 'obtain'],
  put: ['place', 'set', 'position', 'lay', 'situate'],
  use: ['utilize', 'employ', 'apply', 'operate', 'leverage'],
  try: ['attempt', 'endeavor', 'strive', 'aim', 'seek'],
  find: ['discover', 'locate', 'uncover', 'detect', 'identify'],
  keep: ['maintain', 'preserve', 'retain', 'sustain', 'hold'],
  move: ['shift', 'transfer', 'relocate', 'transport'],
  work: ['labor', 'toil', 'operate', 'function', 'perform'],
  hold: ['grasp', 'grip', 'clutch', 'retain', 'maintain'],
  write: ['compose', 'draft', 'author', 'pen', 'inscribe'],
  read: ['study', 'examine', 'review', 'peruse', 'scan'],
  learn: ['study', 'discover', 'master', 'absorb', 'grasp'],
  teach: ['instruct', 'educate', 'train', 'coach', 'tutor'],
  lead: ['guide', 'direct', 'conduct', 'steer', 'head'],
  follow: ['pursue', 'trail', 'track', 'shadow', 'accompany'],
  leave: ['depart', 'exit', 'abandon', 'vacate', 'withdraw'],
  come: ['arrive', 'approach', 'appear', 'reach', 'emerge'],
  go: ['proceed', 'travel', 'advance', 'depart', 'journey'],
  see: ['observe', 'notice', 'witness', 'perceive', 'view'],
  look: ['glance', 'gaze', 'peer', 'stare', 'observe'],
  hear: ['listen', 'perceive', 'detect', 'overhear'],
  feel: ['sense', 'experience', 'perceive', 'detect', 'notice'],
  begin: ['start', 'commence', 'initiate', 'launch', 'undertake'],
  start: ['begin', 'commence', 'initiate', 'launch', 'embark'],
  end: ['finish', 'conclude', 'terminate', 'complete', 'cease'],
  stop: ['halt', 'cease', 'discontinue', 'pause', 'terminate'],
  change: ['alter', 'modify', 'transform', 'adjust', 'revise'],
  help: ['assist', 'aid', 'support', 'facilitate', 'enable'],
  grow: ['expand', 'develop', 'increase', 'flourish', 'thrive'],
  bring: ['carry', 'deliver', 'transport', 'convey', 'fetch'],

  // ── Cognitive / Communication ──
  think: ['believe', 'consider', 'ponder', 'reflect', 'contemplate'],
  know: ['understand', 'realize', 'recognize', 'comprehend', 'grasp'],
  want: ['desire', 'wish', 'crave', 'seek'],
  need: ['require', 'demand', 'necessitate'],
  like: ['enjoy', 'appreciate', 'prefer', 'favor', 'admire'],
  love: ['adore', 'cherish', 'treasure', 'appreciate'],
  hate: ['despise', 'detest', 'loathe', 'abhor'],
  say: ['state', 'declare', 'mention', 'express', 'remark'],
  tell: ['inform', 'notify', 'advise', 'reveal', 'disclose'],
  ask: ['inquire', 'question', 'request', 'query', 'probe'],
  answer: ['respond', 'reply', 'address', 'resolve'],
  talk: ['speak', 'discuss', 'converse', 'chat', 'communicate'],
  show: ['demonstrate', 'display', 'reveal', 'exhibit', 'present'],
  explain: ['clarify', 'describe', 'illustrate', 'elaborate'],

  // ── Emotions ──
  happy: ['glad', 'joyful', 'pleased', 'content', 'cheerful'],
  sad: ['unhappy', 'sorrowful', 'melancholy', 'gloomy', 'dejected'],
  angry: ['furious', 'irate', 'enraged', 'livid', 'outraged'],
  scared: ['afraid', 'frightened', 'terrified', 'anxious', 'fearful'],
  calm: ['peaceful', 'serene', 'tranquil', 'composed', 'relaxed'],

  // ── Descriptors ──
  important: ['significant', 'crucial', 'essential', 'vital', 'critical'],
  interesting: ['fascinating', 'intriguing', 'compelling', 'engaging'],
  difficult: ['challenging', 'tough', 'demanding', 'complex', 'arduous'],
  easy: ['simple', 'straightforward', 'effortless', 'uncomplicated'],
  hard: ['difficult', 'tough', 'demanding', 'challenging', 'strenuous'],
  simple: ['easy', 'basic', 'straightforward', 'uncomplicated', 'plain'],
  complex: ['complicated', 'intricate', 'elaborate', 'sophisticated'],
  strong: ['powerful', 'robust', 'sturdy', 'mighty', 'forceful'],
  weak: ['feeble', 'frail', 'fragile', 'delicate', 'flimsy'],
  new: ['novel', 'fresh', 'recent', 'modern', 'innovative'],
  old: ['ancient', 'aged', 'vintage', 'antique', 'elderly'],
  long: ['lengthy', 'extended', 'prolonged', 'extensive'],
  short: ['brief', 'concise', 'compact', 'abbreviated'],
  bright: ['brilliant', 'vivid', 'radiant', 'luminous', 'dazzling'],
  dark: ['dim', 'shadowy', 'gloomy', 'murky', 'obscure'],
  hot: ['warm', 'scorching', 'blazing', 'sweltering', 'heated'],
  cold: ['chilly', 'freezing', 'frigid', 'icy', 'frosty'],
  clean: ['spotless', 'pristine', 'tidy', 'immaculate'],
  dirty: ['filthy', 'grimy', 'soiled', 'messy', 'unclean'],
  rich: ['wealthy', 'affluent', 'prosperous', 'opulent'],
  true: ['accurate', 'correct', 'genuine', 'authentic', 'valid'],
  false: ['incorrect', 'untrue', 'inaccurate', 'wrong', 'mistaken'],
  right: ['correct', 'proper', 'appropriate', 'suitable', 'accurate'],
  wrong: ['incorrect', 'mistaken', 'inaccurate', 'improper', 'faulty'],
  different: ['distinct', 'diverse', 'varied', 'unique', 'contrasting'],
  same: ['identical', 'similar', 'equivalent', 'comparable'],
  main: ['primary', 'principal', 'chief', 'central', 'key'],
  real: ['genuine', 'authentic', 'actual', 'legitimate'],
  clear: ['obvious', 'evident', 'apparent', 'transparent', 'distinct'],
  possible: ['feasible', 'viable', 'potential', 'achievable'],
  common: ['frequent', 'widespread', 'prevalent', 'typical', 'usual'],
  rare: ['uncommon', 'unusual', 'scarce', 'exceptional', 'infrequent'],
  special: ['unique', 'distinctive', 'exceptional', 'remarkable'],
  general: ['broad', 'overall', 'widespread', 'universal'],
  specific: ['particular', 'precise', 'exact', 'definite', 'detailed'],

  // ── Quantity ──
  many: ['numerous', 'several', 'multiple', 'countless', 'abundant'],
  few: ['scarce', 'limited', 'sparse', 'rare'],
  some: ['several', 'certain', 'various'],

  // ── Transition / Linking Words ──
  also: ['additionally', 'furthermore', 'moreover', 'likewise'],
  however: ['nevertheless', 'nonetheless', 'yet', 'though'],
  therefore: ['consequently', 'hence', 'thus', 'accordingly'],
  although: ['though', 'while', 'whereas', 'despite'],

  // ── Essay Nouns ──
  problem: ['issue', 'challenge', 'difficulty', 'obstacle', 'dilemma'],
  idea: ['concept', 'notion', 'thought', 'theory', 'proposal'],
  way: ['method', 'approach', 'manner', 'technique', 'strategy'],
  part: ['component', 'element', 'portion', 'segment', 'section'],
  place: ['location', 'area', 'site', 'spot', 'position'],
  world: ['globe', 'planet', 'realm', 'domain'],
  group: ['team', 'collective', 'assembly', 'cluster'],
  point: ['aspect', 'matter', 'detail', 'factor', 'element'],
  fact: ['truth', 'reality', 'certainty', 'detail'],
  result: ['outcome', 'consequence', 'effect', 'finding'],
  reason: ['cause', 'motive', 'basis', 'rationale'],
  power: ['strength', 'force', 'authority', 'influence'],
  area: ['region', 'zone', 'district', 'sector', 'territory'],
  story: ['tale', 'narrative', 'account', 'chronicle'],
  example: ['instance', 'illustration', 'case', 'sample', 'model'],
  study: ['research', 'analysis', 'investigation', 'examination'],
  effect: ['impact', 'influence', 'consequence', 'outcome'],
};
